//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jpsale
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public int OrderId { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string MobileNumber { get; set; }
        public string ProductName { get; set; }
        public string TranscationPrice { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> PurchaseTime { get; set; }
        public System.DateTime DeliverDate { get; set; }
    }
}
