//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jpsale
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string RawPrice { get; set; }
        public string SalePrice { get; set; }
        public string PromotionPrice { get; set; }
        public string AgentPrice { get; set; }
    }
}
